using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WindowsAdvancedFirewallApi.Events
{
	internal enum WFEvents
	{
		WFStartupConfigurationInfo = 2000,
		WFStartupProfileConfigurationInfo = 2001,
		WFGlobalConfigurationChangedEvent = 2002,

		WFProfileConfigurationChangedEvent = 2003,
		WFRuleAddEvent = 2004,
		WFRuleChangeEvent = 2005,
		WFRuleDeleteEvent = 2006,

		WFRuleAddStartupEventMessage = 2007,
		WFGroupPolicySuccessEvent = 2008,
		WFGroupPolicyErrorEvent = 2009,
		WFInterfaceProfileChangedEvent = 2010,
		WFUnableToShowQueryUserNotificationEvent = 2011,
		WFRestoreDefaultsEvent = 2032,
		WFAllFirewallRulesDeletedEvent = 2033,

		#region Audit events
		// Firewall
		SE_AUDITID_ETW_FIREWALL_RULE_ADD = 4946,
		SE_AUDITID_ETW_FIREWALL_RULE_CHANGE = 4947,
		SE_AUDITID_ETW_FIREWALL_RULE_DELETE = 4948,
		SE_AUDITID_ETW_FIREWALL_RESTORE_DEFAULTS = 4949,
		SE_AUDITID_ETW_FIREWALL_SETTING_CHANGE = 4950,
		SE_AUDITID_ETW_FIREWALL_RULE_IGNORED = 4951,
		SE_AUDITID_ETW_FIREWALL_RULE_PARTIALLY_IGNORED = 4952,
		SE_AUDITID_ETW_FIREWALL_RULE_REJECTED = 4953,
		SE_AUDITID_ETW_FIREWALL_GROUP_POLICY_CHANGED = 4954,
		SE_AUDITID_ETW_FIREWALL_PROFILE_CHANGE = 4956,
		SE_AUDITID_ETW_FIREWALL_RESOLUTION_EMPTY = 4957,
		SE_AUDITID_ETW_FIREWALL_RUNTIME_ERROR = 4958,

		// MPS Firewall
		SE_AUDITID_ETW_MPSFIREWALL_GET_POLICY_FAILURE = 5027,
		SE_AUDITID_ETW_MPSFIREWALL_PARSE_POLICY_FAILURE = 5028,
		SE_AUDITID_ETW_FIREWALL_APP_BLOCKED_FROM_LISTENING = 5031,
		SE_AUDITID_ETW_FIREWALL_UPCALL_NOTIFICATION_ERROR = 5032,

		// IPsec
		SE_AUDITID_ETW_IPSEC_AUTHENTICATION_SET_ADD = 5040,
		SE_AUDITID_ETW_IPSEC_AUTHENTICATION_SET_CHANGE = 5041,
		SE_AUDITID_ETW_IPSEC_AUTHENTICATION_SET_DELETE = 5042,
		SE_AUDITID_ETW_IPSEC_CONNECTION_SECURITY_ADD = 5043,
		SE_AUDITID_ETW_IPSEC_CONNECTION_SECURITY_CHANGE = 5044,
		SE_AUDITID_ETW_IPSEC_CONNECTION_SECURITY_DELETE = 5045,
		SE_AUDITID_ETW_IPSEC_CRYPTO_SET_ADD = 5046,
		SE_AUDITID_ETW_IPSEC_CRYPTO_SET_CHANGE = 5047,
		SE_AUDITID_ETW_IPSEC_CRYPTO_SET_DELETE = 5048,
		SE_AUDITID_ETW_IPSEC_SA_DELETED = 5049,
		#endregion
	}
}
